name: Go

on:
  push:
    branch:
      - master
    tags:
      - v*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          export GO111MODULE=off
          go get github.com/GeertJohan/go.rice
          go get github.com/GeertJohan/go.rice/rice
          curl http://kindlegen.s3.amazonaws.com/kindlegen_win32_v2_9.zip | tar -zx
          export GO111MODULE=on

      - name: Build-windows
        env:
          GOOS: windows
        run: |
          go build -ldflags "-s -w" -o kas.exe -v main.go
          zip kas-windows.zip --junk-paths kindle.exe kas.exe

      - name: Build-linux
        env:
          GOOS: linux
        run: go build -ldflags "-s -w" -o kas-linux -v main.go

      - name: Build-osx
        env:
          GOOS: darwin
        run: go build -ldflags "-s -w" -o kas-darwin -v main.go

      - name: upload
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "kas-*"
          tags: true
          draft: false
          overwrite: true
          verbose: true
